Prevent possible error when goal deleted.
Should prevent an error like this:

```
Error: {"message":"Key \"\" for array with keys \"4\" does not exist.","file":"plugins\/Live\/templates\/_profileSummary.twig","line":24}
```

The visitor log / profile fetches currently all goal conversions and does check whether a goal still exists so not sure why it is needed  (in https://github.com/piwik/piwik/blob/3.3.0-b1/plugins/Goals/VisitorDetails.php#L67 ). Where this happened the goal actually exists but the other first 3 goals are deleted.

Here is some output from visitor data and idGoal 4 is definitely set in `goals`
```

["totalConversionsByGoal"]=>
  array(2) {
    [1]=>
    int(0)
    ["idgoal=4"]=>
    int(1)
  }
```